AM_CPPFLAGS = -Wall
AM_CFLAGS	=
AM_CXXFLAGS =
AM_LDFLAGS	=

AM_CPPFLAGS += -I@top_srcdir@/include

noinst_LTLIBRARIES = libgnssxx.la

libgnssxx_la_SOURCES = \
gnssxx.cc \
misc/bytes.cc \
misc/decimal.cc \
misc/istream_line_iterator.cc \
misc/utils.cc \
rinex/ion.cc \
rinex/rinex_compound_field.cc \
rinex/rinex_compound_field_builder.cc \
rinex/rinex_field.cc \
rinex/rinex_file_header.cc \
rinex/rinex_file_satsys.cc \
rinex/rinex_file_type.cc \
rinex/rinex_file_version.cc \
rinex/rinex_header_parser.cc \
rinex/rinex_header_parser_factory.cc \
rinex/rinex_integer_field.cc \
rinex/rinex_metadata.cc \
rinex/rinex_parse_context.cc \
rinex/rinex_parse_navmsg_context.cc \
rinex/rinex_parse_obs_context.cc \
rinex/rinex_parser.cc \
rinex/rinex_parser_factory.cc \
rinex/rinex_real_field.cc \
rinex/rinex_skip_field.cc \
rinex/rinex_string_field.cc \
time/jd.cc \
time/timezone.cc \
time/unixtime.cc
